# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
    - release/*
    - develop
    - master
    - refs/tags/v2.*
    - refs/tags/v3.*
    - refs/tags/v4.*

pr: none

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UseGitVersion@5
  displayName: 'UseGitVersion (preview)'
  inputs:
    versionSpec: '5.x'
    includePrerelease: true
    updateAssemblyInfo: false
  env:
      BUILD_BUILDNUMBER: $(GitVersion.NuGetVersionV2)
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '$(Build.SourcesDirectory)/src/*.csproj'
- task: CmdLine@2
  inputs:
    script: 'dotnet pack $(Build.SourcesDirectory)/src/*.csproj --output $(Build.ArtifactStagingDirectory) --include-symbols -p:Configuration=$(buildConfiguration) -p:Version=$(build.buildNumber)'
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'